// <auto-generated />
using System;
using MedSmarter.Modules.ProductTrace.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSmarter.Modules.ProductTrace.Persistence.Migrations
{
    [DbContext(typeof(ProductTraceDbContext))]
    [Migration("20261009185811_InitialProductTraceSchema")]
    partial class InitialProductTraceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("product_trace")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.OutboxRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer_report_outbox");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_manufacturer_report_outbox_idempotency_key");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_manufacturer_report_outbox_report_id");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_manufacturer_report_outbox_state_next_attempt_at");

                    b.ToTable("manufacturer_report_outbox", "product_trace");
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.ProductRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNormalized")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("batch_normalized");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("batch_number");

                    b.Property<string>("Consistency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("consistency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FindingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("findings_json");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generic_name");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<DateOnly?>("ManufactureDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacture_date");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer_name");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PatientMedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_medication_id");

                    b.Property<string>("PharmacyNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pharmacy_note");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("product_key");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recorded_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Verification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("verification");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_dispensed_product_record");

                    b.HasIndex("BatchNormalized")
                        .HasDatabaseName("ix_dispensed_product_record_batch_normalized");

                    b.HasIndex("PatientId", "DeletedAt")
                        .HasDatabaseName("ix_dispensed_product_record_patient_id_deleted_at");

                    b.HasIndex("PatientId", "BatchNormalized", "ProductKey", "ExpiryDate")
                        .IsUnique()
                        .HasDatabaseName("ux_dispensed_product_record_patient_id_batch_normalized_product_key_expiry_date")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("dispensed_product_record", "product_trace", t =>
                        {
                            t.HasCheckConstraint("ck_dispensed_product_record_batch", "length(batch_number) BETWEEN 1 AND 40");

                            t.HasCheckConstraint("ck_dispensed_product_record_dates", "manufacture_date IS NULL OR manufacture_date < expiry_date");

                            t.HasCheckConstraint("ck_dispensed_product_record_identity", "medication_id IS NOT NULL OR length(product_name) > 0");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.ProductVersionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("ProductRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_record_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_dispensed_product_record_version");

                    b.HasIndex("ProductRecordId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_dispensed_product_record_version_product_record_id_version_number");

                    b.ToTable("dispensed_product_record_version", "product_trace");
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.ReportEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer_report_event");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_manufacturer_report_event_report_id");

                    b.ToTable("manufacturer_report_event", "product_trace");
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.ReportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("ClientRequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_request_id");

                    b.Property<Guid?>("ConsentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("DurationOfUseDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_of_use_days");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<bool>("IncludeConcomitant")
                        .HasColumnType("boolean")
                        .HasColumnName("include_concomitant");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<bool>("IsMockDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mock_delivery");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("issue_type");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date")
                        .HasColumnName("occurred_on");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("ProductRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_record_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("reference");

                    b.Property<string>("ReviewDecision")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_decision");

                    b.Property<bool>("ReviewRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("review_required");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reviewer_note");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer_safety_report");

                    b.HasIndex("ProductRecordId")
                        .HasDatabaseName("ix_manufacturer_safety_report_product_record_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_manufacturer_safety_report_reference");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_manufacturer_safety_report_status");

                    b.HasIndex("PatientId", "ClientRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_manufacturer_safety_report_patient_id_client_request_id")
                        .HasFilter("client_request_id IS NOT NULL");

                    b.HasIndex("PatientId", "Status")
                        .HasDatabaseName("ix_manufacturer_safety_report_patient_id_status");

                    b.ToTable("manufacturer_safety_report", "product_trace", t =>
                        {
                            t.HasCheckConstraint("ck_manufacturer_safety_report_duration", "duration_of_use_days IS NULL OR duration_of_use_days BETWEEN 0 AND 36500");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.OutboxRow", b =>
                {
                    b.HasOne("MedSmarter.Modules.ProductTrace.Persistence.ReportRow", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manufacturer_report_outbox_manufacturer_safety_report_report_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.ProductVersionRow", b =>
                {
                    b.HasOne("MedSmarter.Modules.ProductTrace.Persistence.ProductRecordRow", null)
                        .WithMany()
                        .HasForeignKey("ProductRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispensed_product_record_version_dispensed_product_record_product_record_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.ReportEventRow", b =>
                {
                    b.HasOne("MedSmarter.Modules.ProductTrace.Persistence.ReportRow", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manufacturer_report_event_manufacturer_safety_report_report_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.ProductTrace.Persistence.ReportRow", b =>
                {
                    b.HasOne("MedSmarter.Modules.ProductTrace.Persistence.ProductRecordRow", null)
                        .WithMany()
                        .HasForeignKey("ProductRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_manufacturer_safety_report_dispensed_product_record_product_record_id");
                });
#pragma warning restore 612, 618
        }
    }
}
