// <auto-generated />
using System;
using MedSmarter.Modules.Medications.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSmarter.Modules.Medications.Persistence.Migrations
{
    [DbContext(typeof(MedicationsDbContext))]
    partial class MedicationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("medications")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.ActiveIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AtcCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("atc_code");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lifecycle");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_fa");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("validation");

                    b.HasKey("Id")
                        .HasName("pk_active_ingredient");

                    b.HasIndex("AtcCode")
                        .HasDatabaseName("ix_active_ingredient_atc_code");

                    b.ToTable("active_ingredient", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_active_ingredient_has_name", "name_en IS NOT NULL OR name_fa IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_fa");

                    b.HasKey("Id")
                        .HasName("pk_brand");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_brand_manufacturer_id");

                    b.ToTable("brand", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_brand_has_name", "name_en IS NOT NULL OR name_fa IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.DrugInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngredientAId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_a_id");

                    b.Property<Guid>("IngredientBId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_b_id");

                    b.Property<string>("ManagementEn")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("management_en");

                    b.Property<string>("ManagementFa")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("management_fa");

                    b.Property<string>("MechanismEn")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("mechanism_en");

                    b.Property<string>("MechanismFa")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("mechanism_fa");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_drug_interaction");

                    b.HasIndex("IngredientBId")
                        .HasDatabaseName("ix_drug_interaction_ingredient_b_id");

                    b.HasIndex("RevisionId")
                        .HasDatabaseName("ix_drug_interaction_revision_id");

                    b.HasIndex("IngredientAId", "IngredientBId")
                        .IsUnique()
                        .HasDatabaseName("ux_drug_interaction_ingredient_a_id_ingredient_b_id");

                    b.ToTable("drug_interaction", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_drug_interaction_order", "ingredient_a_id < ingredient_b_id");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.IngredientSynonym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_ingredient_synonym");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_ingredient_synonym_ingredient_id");

                    b.ToTable("ingredient_synonym", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.KnowledgeRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_revision");

                    b.HasIndex("SourceId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_revision_source_id_label");

                    b.ToTable("knowledge_revision", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.KnowledgeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("license_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<bool?>("RedistributionAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("redistribution_allowed");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<string>("UsageRestrictions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("usage_restrictions");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("validation");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_source");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_knowledge_source_name_version");

                    b.ToTable("knowledge_source", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country")
                        .IsFixedLength();

                    b.Property<string>("ManufacturerCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manufacturer_code");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_fa");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer");

                    b.HasIndex("ManufacturerCode")
                        .IsUnique()
                        .HasDatabaseName("ux_manufacturer_manufacturer_code");

                    b.ToTable("manufacturer", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_manufacturer_has_name", "name_en IS NOT NULL OR name_fa IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DosageFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("dosage_form_id");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lifecycle");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_fa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("validation");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_medication");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_medication_brand_id");

                    b.HasIndex("DosageFormId")
                        .HasDatabaseName("ix_medication_dosage_form_id");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_medication_manufacturer_id");

                    b.HasIndex("Lifecycle", "Validation")
                        .HasDatabaseName("ix_medication_lifecycle_validation");

                    b.ToTable("medication", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_medication_demo_not_validated", "NOT (is_demo AND validation = 'Validated')");

                            t.HasCheckConstraint("ck_medication_has_name", "name_en IS NOT NULL OR name_fa IS NOT NULL");

                            t.HasCheckConstraint("ck_medication_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationClassification", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.HasKey("MedicationId", "TermId")
                        .HasName("pk_medication_classification");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_medication_classification_term_id");

                    b.ToTable("medication_classification", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("scheme");

                    b.Property<Guid>("SourceRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_revision_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_medication_identifier");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("ix_medication_identifier_medication_id");

                    b.HasIndex("SourceRevisionId")
                        .HasDatabaseName("ix_medication_identifier_source_revision_id");

                    b.HasIndex("Scheme", "Value")
                        .IsUnique()
                        .HasDatabaseName("ux_medication_identifier_scheme_value");

                    b.ToTable("medication_identifier", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationIngredient", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("PerUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("per_unit");

                    b.Property<string>("StrengthUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("strength_unit");

                    b.Property<decimal?>("StrengthValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("strength_value");

                    b.HasKey("MedicationId", "IngredientId")
                        .HasName("pk_medication_ingredient");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_medication_ingredient_ingredient_id");

                    b.ToTable("medication_ingredient", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_medication_ingredient_strength", "(strength_value IS NULL AND strength_unit IS NULL) OR (strength_value > 0 AND strength_unit IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationRoute", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.HasKey("MedicationId", "TermId")
                        .HasName("pk_medication_route");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_medication_route_term_id");

                    b.ToTable("medication_route", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationSearchTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("Normalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized");

                    b.HasKey("Id")
                        .HasName("pk_medication_search_term");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("ix_medication_search_term_medication_id");

                    b.HasIndex("Normalized")
                        .HasDatabaseName("ix_medication_search_term_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Normalized"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Normalized"), new[] { "gin_trgm_ops" });

                    b.ToTable("medication_search_term", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Frequency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("frequency");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("Population")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("population");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<string>("Severity")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("TextEn")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text_en");

                    b.Property<string>("TextFa")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text_fa");

                    b.HasKey("Id")
                        .HasName("pk_medication_statement");

                    b.HasIndex("RevisionId")
                        .HasDatabaseName("ix_medication_statement_revision_id");

                    b.HasIndex("MedicationId", "Kind")
                        .HasDatabaseName("ix_medication_statement_medication_id_kind");

                    b.ToTable("medication_statement", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_medication_statement_has_text", "text_en IS NOT NULL OR text_fa IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationSynonym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_medication_synonym");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("ix_medication_synonym_medication_id");

                    b.ToTable("medication_synonym", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("change_reason");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_medication_version");

                    b.HasIndex("MedicationId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_medication_version_medication_id_version_number");

                    b.ToTable("medication_version", "medications");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.ReferenceTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFa")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_fa");

                    b.HasKey("Id")
                        .HasName("pk_reference_term");

                    b.HasIndex("Kind", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_reference_term_kind_code");

                    b.ToTable("reference_term", "medications", t =>
                        {
                            t.HasCheckConstraint("ck_reference_term_has_name", "name_en IS NOT NULL OR name_fa IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.Brand", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_brand_manufacturer_manufacturer_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.DrugInteraction", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.ActiveIngredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drug_interaction_active_ingredient_ingredient_a_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.ActiveIngredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drug_interaction_active_ingredient_ingredient_b_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.KnowledgeRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drug_interaction_knowledge_revision_revision_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.IngredientSynonym", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.ActiveIngredient", null)
                        .WithMany("Synonyms")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_synonym_active_ingredient_ingredient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.KnowledgeRevision", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.KnowledgeSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_revision_knowledge_source_source_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.Medication", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medication_brand_brand_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.ReferenceTerm", null)
                        .WithMany()
                        .HasForeignKey("DosageFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_reference_term_dosage_form_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medication_manufacturer_manufacturer_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationClassification", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany("Classifications")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_classification_medication_medication_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.ReferenceTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_classification_reference_term_term_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationIdentifier", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany("Identifiers")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_identifier_medication_medication_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.KnowledgeRevision", null)
                        .WithMany()
                        .HasForeignKey("SourceRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_identifier_knowledge_revision_source_revision_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationIngredient", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.ActiveIngredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_ingredient_active_ingredient_ingredient_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_ingredient_medication_medication_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationRoute", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany("Routes")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_route_medication_medication_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.ReferenceTerm", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_route_reference_term_term_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationSearchTerm", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_search_term_medication_medication_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationStatement", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany("Statements")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_statement_medication_medication_id");

                    b.HasOne("MedSmarter.Modules.Medications.Domain.KnowledgeRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_statement_knowledge_revision_revision_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationSynonym", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany("Synonyms")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_synonym_medication_medication_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.MedicationVersion", b =>
                {
                    b.HasOne("MedSmarter.Modules.Medications.Domain.Medication", null)
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_version_medication_medication_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.ActiveIngredient", b =>
                {
                    b.Navigation("Synonyms");
                });

            modelBuilder.Entity("MedSmarter.Modules.Medications.Domain.Medication", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("Identifiers");

                    b.Navigation("Ingredients");

                    b.Navigation("Routes");

                    b.Navigation("Statements");

                    b.Navigation("Synonyms");
                });
#pragma warning restore 612, 618
        }
    }
}
