#!/usr/bin/env node
// Interactive smoke test of key flows against `npm run preview` (Chromium via playwright-core).
import { chromium } from "playwright-core";
const base = process.env.BASE ?? "http://127.0.0.1:4173";
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, reducedMotion: "reduce" });
await ctx.addInitScript(() => {
  localStorage.setItem("ms.locale", "en");
  // sign in as the fictional demo patient (same storage format the demo login writes)
  if (!sessionStorage.getItem("flow-seeded")) { sessionStorage.setItem("flow-seeded", "1"); localStorage.setItem("ms.auth.demo-session", JSON.stringify({ accountId: "demo-patient", sessionId: "flow", expiresAt: Date.now() + 86_400_000 })); }
});
const p = await ctx.newPage();
const fails = [];
const check = (ok, msg) => { if (!ok) fails.push(msg); console.log(ok ? "ok  " : "FAIL", msg); };

// 1. assistant: ask, sources, evidence, escalation
await p.goto(base + "/app/patient/assistant", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /Can Demopril and Nocturin/ }).click();
await p.getByText("Source match").waitFor();
check(await p.getByText("Medium", { exact: true }).count() > 0, "answer shows confidence level");
check(await p.getByText(/Informational only/).count() > 0, "answer shows safety notice");
await p.getByRole("button", { name: "View evidence" }).click();
check(await p.getByRole("dialog", { name: "Evidence" }).isVisible(), "evidence drawer opens");
await p.keyboard.press("Escape");
check(!(await p.getByRole("dialog").count()), "Escape closes the drawer");
await p.getByRole("button", { name: "Send to pharmacist" }).click();
await p.getByRole("dialog").getByRole("button", { name: "Send", exact: true }).click();
await p.getByText("Sent to pharmacist").first().waitFor();
check(true, "escalation to pharmacist completes");
await p.screenshot({ path: "/tmp/qa/flow-assistant.png", fullPage: true });

// red flag path is static, not an AI answer
await p.getByRole("textbox", { name: "Message to the assistant" }).fill("I have chest pain");
await p.getByRole("button", { name: "Send message" }).click();
await p.getByText("This may be urgent").waitFor();
check(await p.getByText(/fixed text, not generated by AI/).count() > 0, "red-flag message is fixed text");

// refusal on unknown question
await p.getByRole("textbox", { name: "Message to the assistant" }).fill("Tell me about quantum tunnelling");
await p.getByRole("button", { name: "Send message" }).click();
await p.getByText(/will not guess|not guess/).first().waitFor();
check(true, "unknown question is refused, not guessed");

// 2. patient home: mark dose taken + undo
await p.goto(base + "/app/patient", { waitUntil: "networkidle" });
const took = p.getByRole("button", { name: "I took it" });
if (await took.count()) {
  await took.click();
  await p.getByText(/recorded as taken/).waitFor();
  check(true, "dose recorded toast");
  await p.getByRole("button", { name: "Undo" }).click();
  check(true, "undo available");
}

// 3. DEMO DEV account switching changes the whole information architecture (and is labelled as DEMO DEV)
await p.getByRole("button", { name: "Account menu" }).click();
check((await p.getByRole("menuitem", { name: /DEMO DEV/ }).count()) > 2, "account switching is labelled DEMO DEV");
await p.getByRole("menuitem", { name: /DEMO DEV.*Industry/ }).click();
await p.waitForURL("**/app/industry");
await p.getByText(/Aggregate data only/).first().waitFor({ timeout: 8000 }).catch(() => undefined);
check(await p.getByText(/Aggregate data only/).count() > 0, "industry shows aggregate-only banner");
check((await p.getByRole("link", { name: /Patients$/ }).count()) === 0, "industry has no patient list");
await p.goto(base + "/app/patient", { waitUntil: "networkidle" });
check(await p.getByTestId("unauthorized").count() > 0, "industry user opening the patient app gets the no-access page");

// 3b. sign out ends the session and protected pages redirect to the login screen
await p.getByRole("button", { name: "Account menu" }).click();
await p.getByRole("menuitem", { name: "Sign out" }).click();
await p.waitForURL("**/login");
await p.goto(base + "/app/industry", { waitUntil: "networkidle" });
check(new URL(p.url()).pathname === "/login", "after sign-out protected pages redirect to /login");
await p.getByRole("button", { name: "Sign in as DEMO Physician — Dr. Karimi" }).click();
await p.waitForURL("**/app/physician");
check(true, "signing in as the physician opens the physician dashboard");

// 4. keyboard: skip link + tabs
await p.goto(base + "/app/physician/patients/pt-sara", { waitUntil: "networkidle" });
await p.getByRole("tab", { name: "Overview" }).focus();
await p.keyboard.press("ArrowRight");
check((await p.getByRole("tab", { selected: true }).innerText()) === "Medications", "ArrowRight moves to next tab");
await b.close();
process.exit(fails.length ? 1 : 0);
