#!/usr/bin/env node
// Generates typed constants + shared JSON copies from security/access-catalog.json (single source of truth for
// roles, permissions, role->permission mapping and FICTIONAL demo identities).
//   node security/build.mjs          write generated files
//   node security/build.mjs --check  fail if generated files are stale or the catalog is inconsistent
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const raw = readFileSync(join(root, "security/access-catalog.json"), "utf8");
const cat = JSON.parse(raw);
let stale = 0;

// ---- consistency rules (deny-by-default catalog) ----
const problems = [];
const permNames = new Set(cat.permissions.map((p) => p.name));
if (permNames.size !== cat.permissions.length) problems.push("duplicate permission names");
for (const p of cat.permissions) {
  if (!/^[a-z][a-z0-9-]*(\.[a-z][a-z0-9-]*)+$/.test(p.name)) problems.push(`bad permission name ${p.name}`);
  if (!["subject", "organization", "aggregate", "own", "global"].includes(p.kind)) problems.push(`bad kind ${p.name}`);
  if (p.kind === "subject" && !cat.dataScopes.includes(p.dataScope)) problems.push(`subject permission without data scope ${p.name}`);
}
for (const g of cat.granteeFreePurposes) if (!cat.consentPurposes.includes(g)) problems.push(`grantee-free purpose ${g} is not a consent purpose`);
const roleNames = new Set();
for (const r of cat.roles) {
  roleNames.add(r.name);
  for (const p of r.permissions) if (!permNames.has(p)) problems.push(`role ${r.name} references unknown permission ${p}`);
  if (new Set(r.permissions).size !== r.permissions.length) problems.push(`role ${r.name} has duplicate permissions`);
}
// least privilege: roles without a clinical purpose must never carry subject-scoped (patient data) permissions
const subjectPerms = new Set(cat.permissions.filter((p) => p.kind === "subject").map((p) => p.name));
for (const r of cat.roles) {
  if (["SystemAdmin", "PharmaceuticalCompany", "Researcher", "ContentManager", "AIManager", "PharmacyAdmin"].includes(r.name)) {
    for (const p of r.permissions) if (subjectPerms.has(p)) problems.push(`${r.name} must not hold patient-data permission ${p}`);
  }
}
for (const a of cat.demoAccounts) for (const r of a.roles) if (!roleNames.has(r.role)) problems.push(`account ${a.id} has unknown role ${r.role}`);
if (/password|secret|token/i.test(JSON.stringify(cat.demoAccounts))) problems.push("demo accounts must not contain credential-like fields");
if (problems.length) {
  console.error("ACCESS CATALOG PROBLEMS:\n - " + problems.join("\n - "));
  process.exit(1);
}

function emit(rel, content) {
  const path = join(root, rel);
  if (check) {
    const cur = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (cur !== content) { console.error(`STALE: ${rel} (run: node security/build.mjs)`); stale++; }
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

const pascal = (s) => s.split(/[.\-]/).map((x) => x[0].toUpperCase() + x.slice(1)).join("");
const camel = (s) => { const p = pascal(s); return p[0].toLowerCase() + p.slice(1); };

// ---- C# ----
const cs = `// <auto-generated> from security/access-catalog.json by security/build.mjs - do not edit. </auto-generated>
namespace MedSmarter.Modules.Identity.Contracts;

/// <summary>Permission names (the only strings authorization may check).</summary>
public static class Permissions
{
${cat.permissions.map((p) => `    public const string ${pascal(p.name)} = "${p.name}";`).join("\n")}
}

public static class RoleNames
{
${cat.roles.map((r) => `    public const string ${r.name} = "${r.name}";`).join("\n")}
}

/// <summary>Consent purposes.</summary>
public static class ConsentPurposes
{
${cat.consentPurposes.map((p) => `    public const string ${p} = "${p}";`).join("\n")}

    /// <summary>Purposes that have no grantee (the data is not given to a person or organization): consent is recorded for the purpose itself.</summary>
    public static readonly string[] GranteeFree = [${cat.granteeFreePurposes.map((p) => `"${p}"`).join(", ")}];
}

/// <summary>Consent data scopes (data categories).</summary>
public static class DataScopes
{
${cat.dataScopes.map((s) => `    public const string ${pascal(s.replace(/_/g, "-"))} = "${s}";`).join("\n")}
}
`;
emit("src/Modules/Identity/MedSmarter.Modules.Identity.Contracts/Generated/AccessCatalog.g.cs", cs);

// ---- TypeScript ----
const ts = `// GENERATED from security/access-catalog.json by security/build.mjs - do not edit.
export const permissions = {
${cat.permissions.map((p) => `  ${camel(p.name)}: "${p.name}",`).join("\n")}
} as const;
export type Permission = (typeof permissions)[keyof typeof permissions];

export const roleNames = [${cat.roles.map((r) => `"${r.name}"`).join(", ")}] as const;
export type RoleName = (typeof roleNames)[number];

export const consentPurposes = [${cat.consentPurposes.map((p) => `"${p}"`).join(", ")}] as const;
export type ConsentPurpose = (typeof consentPurposes)[number];
export const granteeFreePurposes: readonly ConsentPurpose[] = [${cat.granteeFreePurposes.map((p) => `"${p}"`).join(", ")}];

export const dataScopes = [${cat.dataScopes.map((s) => `"${s}"`).join(", ")}] as const;
export type DataScope = (typeof dataScopes)[number];
`;
emit("web/src/auth/access.g.ts", ts);
emit("web/src/shared/access-catalog.json", raw);

// ---- Dart ----
const dart = `// GENERATED from security/access-catalog.json by security/build.mjs - do not edit.
// ignore_for_file: public_member_api_docs

abstract final class Permissions {
${cat.permissions.map((p) => `  static const ${camel(p.name)} = '${p.name}';`).join("\n")}
}

abstract final class RoleNames {
${cat.roles.map((r) => `  static const ${camel(r.name)} = '${r.name}';`).join("\n")}
}

abstract final class ConsentPurposes {
${cat.consentPurposes.map((p) => `  static const ${p[0].toLowerCase() + p.slice(1)} = '${p}';`).join("\n")}
  static const granteeFree = [${cat.granteeFreePurposes.map((p) => `'${p}'`).join(", ")}];
}

abstract final class DataScopes {
${cat.dataScopes.map((s) => `  static const ${camel(s.replace(/_/g, "-"))} = '${s}';`).join("\n")}
}
`;
emit("mobile/lib/auth/access.g.dart", dart);
emit("mobile/assets/shared/access-catalog.json", raw);

if (check && stale) process.exit(1);
console.log(check ? "security artefacts up to date" : `security: ${cat.permissions.length} permissions, ${cat.roles.length} roles, ${cat.demoAccounts.length} demo accounts`);
