#!/usr/bin/env node
// Generates every platform artefact from the shared sources in design/.
//   node design/build.mjs          write generated files
//   node design/build.mjs --check  fail (exit 1) if generated files are stale or a contrast rule fails
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const tokens = JSON.parse(readFileSync(join(root, "design/tokens.json"), "utf8"));
let stale = 0;

function emit(rel, content) {
  const path = join(root, rel);
  if (check) {
    const cur = existsSync(path) ? readFileSync(path, "utf8") : null;
    // Generated Dart may be re-formatted by `dart format`; compare ignoring formatting only.
    const norm = (t) => (rel.endsWith(".dart") && t ? t.replace(/\s+/g, "").replace(/,([)\]}])/g, "$1") : t);
    if (norm(cur) !== norm(content)) {
      console.error(`STALE: ${rel} (run: node design/build.mjs)`);
      stale++;
    }
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

// ---------- colour resolution + contrast ----------
const resolve = (ref) => {
  if (ref.startsWith("#")) return ref.toUpperCase();
  const [g, s] = ref.split(".");
  const v = tokens.palette[g]?.[s];
  if (!v) throw new Error(`Unknown palette reference ${ref}`);
  return v.toUpperCase();
};
const modes = {};
for (const m of ["light", "dark"]) {
  modes[m] = Object.fromEntries(Object.entries(tokens.color[m]).map(([k, v]) => [k, resolve(v)]));
}
const lum = (hex) => {
  const c = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255).map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const ratio = (a, b) => {
  const [l1, l2] = [lum(a), lum(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
};
let contrastFailures = 0;
for (const m of ["light", "dark"]) {
  for (const [fg, bg, min] of tokens.contrast.pairs) {
    const r = ratio(modes[m][fg], modes[m][bg]);
    if (r < min) {
      console.error(`CONTRAST FAIL [${m}] ${fg} on ${bg}: ${r.toFixed(2)} < ${min}`);
      contrastFailures++;
    }
  }
}
if (contrastFailures) process.exit(1);
if (!check) console.log(`contrast: ${tokens.contrast.pairs.length * 2} pairs OK`);

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const px = (n) => (n === 0 ? "0" : `${n}px`);
const rgba = (hex, a) => `rgb(${[1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16)).join(" ")} / ${a})`;

// ---------- CSS ----------
const shadowCss = (mode, level) => {
  const base = mode === "light" ? modes.light.scrim : "#000000";
  const layers = tokens.elevation[mode][level];
  return layers.length ? layers.map((l) => `0 ${px(l.y)} ${px(l.blur)} ${px(l.spread)} ${rgba(base, l.alpha)}`).join(", ") : "none";
};
const colorVars = (mode) => Object.entries(modes[mode]).map(([k, v]) => `  --color-${kebab(k)}: ${v};`).join("\n") +
  "\n" + Object.keys(tokens.elevation[mode]).map((l) => `  --shadow-${l}: ${shadowCss(mode, l)};`).join("\n") +
  `\n  color-scheme: ${mode};`;
const ty = tokens.typography;
const typeVars = (scale) => Object.entries(scale).map(([n, t]) => {
  const k = kebab(n);
  return `  --text-${k}-size: ${t.size / 16}rem;\n  --text-${k}-line: ${t.line / 16}rem;\n  --text-${k}-weight: ${t.weight};`;
}).join("\n");
const easing = (e) => `cubic-bezier(${e.join(", ")})`;
const staticVars = [
  `  --font-family: "${ty.fontFamily}", ${ty.fontFallback.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ")};`,
  typeVars(ty.scale),
  ...Object.entries(tokens.space).map(([k, v]) => `  --space-${k}: ${v / 16}rem;`),
  ...Object.entries(tokens.radius).map(([k, v]) => `  --radius-${k}: ${v === 999 ? "999px" : px(v)};`),
  ...Object.entries(tokens.iconSize).map(([k, v]) => `  --icon-${k}: ${px(v)};`),
  ...Object.entries(tokens.controlHeight).map(([k, v]) => `  --control-${k}: ${px(v)};`),
  `  --touch-target-min: ${px(tokens.touchTargetMin)};`,
  ...Object.entries(tokens.breakpoints).map(([k, v]) => `  --bp-${k}: ${px(v)};`),
  ...Object.entries(tokens.layout).map(([k, v]) => `  --layout-${kebab(k)}: ${px(v)};`),
  ...Object.entries(tokens.motion.duration).map(([k, v]) => `  --duration-${k}: ${v}ms;`),
  ...Object.entries(tokens.motion.easing).map(([k, v]) => `  --ease-${k}: ${easing(v)};`),
  ...Object.entries(tokens.zIndex).map(([k, v]) => `  --z-${kebab(k)}: ${v};`),
].join("\n");
const utilClasses = Object.keys(ty.scale).map((n) => {
  const k = kebab(n);
  return `.t-${k} { font-size: var(--text-${k}-size); line-height: var(--text-${k}-line); font-weight: var(--text-${k}-weight); }`;
}).join("\n");
const css = `/* GENERATED by design/build.mjs from design/tokens.json - do not edit. */
:root {
${staticVars}
${colorVars("light")}
}

:root[data-theme="dark"] {
${colorVars("dark")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${colorVars("dark").split("\n").map((l) => "  " + l).join("\n")}
  }
}

@media (max-width: ${tokens.breakpoints.medium - 1}px) {
  :root {
${typeVars(ty.compactScale).split("\n").map((l) => "  " + l).join("\n")}
  }
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-instant: 0.01ms;
    --duration-fast: 0.01ms;
    --duration-base: 0.01ms;
    --duration-slow: 0.01ms;
  }
}

${utilClasses}
`;
emit("web/src/design/tokens.css", css);

// ---------- TypeScript ----------
const ts = `// GENERATED by design/build.mjs from design/tokens.json - do not edit.
export const breakpoints = ${JSON.stringify(tokens.breakpoints)} as const;
export const layout = ${JSON.stringify(tokens.layout)} as const;
export const colorNames = ${JSON.stringify(Object.keys(tokens.color.light))} as const;
export type ColorName = (typeof colorNames)[number];
export const themeColors = ${JSON.stringify(modes)} as const;
export type Breakpoint = keyof typeof breakpoints;
`;
emit("web/src/design/tokens.g.ts", ts);

// ---------- Dart ----------
const hexDart = (h) => `Color(0xFF${h.slice(1)})`;
const colorFields = Object.keys(tokens.color.light);
const dartColors = (m) => `AppColors(\n${colorFields.map((f) => `    ${f}: ${hexDart(modes[m][f])},`).join("\n")}\n  )`;
const dartShadows = (mode) => Object.keys(tokens.elevation[mode]).map((lvl) => {
  const base = mode === "light" ? modes.light.scrim : "#000000";
  const items = tokens.elevation[mode][lvl].map((l) => `BoxShadow(color: Color.fromRGBO(${[1, 3, 5].map((i) => parseInt(base.slice(i, i + 2), 16)).join(", ")}, ${l.alpha}), offset: Offset(0, ${l.y}), blurRadius: ${l.blur}, spreadRadius: ${l.spread})`);
  return `    ${lvl}: [${items.join(", ")}],`;
}).join("\n");
const typeDart = (scale) => Object.entries(scale).map(([n, t]) => `  static const ${n} = TypeToken(${t.size}, ${t.line}, FontWeight.w${t.weight});`).join("\n");
const dart = `// GENERATED by design/build.mjs from design/tokens.json - do not edit.
// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

class AppColors {
  const AppColors({
${colorFields.map((f) => `    required this.${f},`).join("\n")}
  });

${colorFields.map((f) => `  final Color ${f};`).join("\n")}

  static const light = ${dartColors("light")};
  static const dark = ${dartColors("dark")};
}

abstract final class Space {
${Object.entries(tokens.space).map(([k, v]) => `  static const double s${k} = ${v};`).join("\n")}
}

abstract final class Radii {
${Object.entries(tokens.radius).map(([k, v]) => `  static const double ${k} = ${v};`).join("\n")}
}

abstract final class IconSizes {
${Object.entries(tokens.iconSize).map(([k, v]) => `  static const double ${k} = ${v};`).join("\n")}
}

abstract final class ControlHeights {
${Object.entries(tokens.controlHeight).map(([k, v]) => `  static const double ${k} = ${v};`).join("\n")}
  static const double touchTargetMin = ${tokens.touchTargetMin};
}

abstract final class Breakpoints {
${Object.entries(tokens.breakpoints).map(([k, v]) => `  static const double ${k} = ${v};`).join("\n")}
}

abstract final class LayoutTokens {
${Object.entries(tokens.layout).map(([k, v]) => `  static const double ${k} = ${v};`).join("\n")}
}

abstract final class Motion {
${Object.entries(tokens.motion.duration).map(([k, v]) => `  static const Duration ${k} = Duration(milliseconds: ${v});`).join("\n")}
${Object.entries(tokens.motion.easing).map(([k, v]) => `  static const Curve ${k} = Cubic(${v.join(", ")});`).join("\n")}
}

class TypeToken {
  const TypeToken(this.size, this.line, this.weight);
  final double size;
  final double line;
  final FontWeight weight;
  double get height => line / size;
}

abstract final class TypeScale {
  static const String fontFamily = '${ty.fontFamily}';
${typeDart(ty.scale)}
}

abstract final class TypeScaleCompact {
${typeDart(ty.compactScale)}
}

abstract final class Elevations {
  static const light = <int, List<BoxShadow>>{
${dartShadows("light").replace(/^    (\d):/gm, "    $1:")}
  };
  static const dark = <int, List<BoxShadow>>{
${dartShadows("dark")}
  };
}
`;
emit("mobile/lib/design/tokens.g.dart", dart);

// ---------- strings + demo data ----------
const strPath = join(root, "design/i18n/strings.mjs");
if (existsSync(strPath)) {
  const { strings } = await import(pathToFileURL(strPath).href);
  const en = {}, fa = {};
  for (const [k, [e, f]] of Object.entries(strings)) {
    if (!e || !f) throw new Error(`Missing translation for ${k}`);
    const ph = (s) => [...s.matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(",");
    if (ph(e) !== ph(f)) throw new Error(`Placeholder mismatch for ${k}`);
    en[k] = e; fa[k] = f;
  }
  for (const [name, obj] of [["en", en], ["fa", fa]]) {
    const body = JSON.stringify(obj, null, 2) + "\n";
    emit(`web/src/shared/${name}.json`, body);
    emit(`mobile/assets/shared/${name}.json`, body);
  }
  if (!check) console.log(`i18n: ${Object.keys(en).length} keys`);
}
const demoPath = join(root, "design/mock/demo-data.mjs");
if (existsSync(demoPath)) {
  const { demoData } = await import(pathToFileURL(demoPath).href);
  const body = JSON.stringify(demoData, null, 2) + "\n";
  emit("web/src/shared/demo-data.json", body);
  emit("mobile/assets/shared/demo-data.json", body);
}

// ---------- icons ----------
const iconsPath = join(root, "design/icons.mjs");
if (existsSync(iconsPath)) {
  const { icons, directional } = await import(pathToFileURL(iconsPath).href);
  emit(
    "web/src/components/ui/icons.g.ts",
    `// GENERATED by design/build.mjs from design/icons.mjs - do not edit.\nexport const icons = ${JSON.stringify(icons, null, 2)} as const;\nexport const directional = ${JSON.stringify(directional)} as const;\n`,
  );
  const dartEntries = Object.entries(icons).map(([k, v]) => `  '${k}': '${String(v).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}',`).join("\n");
  emit(
    "mobile/lib/design/icons.g.dart",
    `// GENERATED by design/build.mjs from design/icons.mjs - do not edit.\n// ignore_for_file: public_member_api_docs\nconst Map<String, String> appIconPaths = {\n${dartEntries}\n};\n\nconst Set<String> directionalIcons = {${directional.map((d) => `'${d}'`).join(", ")}};\n`,
  );
}

if (check && stale) process.exit(1);
if (check) console.log("design artefacts up to date");
