// GENERATED by design/build.mjs from design/tokens.json - do not edit.
// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

class AppColors {
  const AppColors({
    required this.primary,
    required this.onPrimary,
    required this.primaryHover,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.accent,
    required this.onAccent,
    required this.accentContainer,
    required this.onAccentContainer,
    required this.success,
    required this.onSuccess,
    required this.successContainer,
    required this.onSuccessContainer,
    required this.warning,
    required this.onWarning,
    required this.warningContainer,
    required this.onWarningContainer,
    required this.danger,
    required this.onDanger,
    required this.dangerContainer,
    required this.onDangerContainer,
    required this.info,
    required this.onInfo,
    required this.infoContainer,
    required this.onInfoContainer,
    required this.background,
    required this.surface,
    required this.surfaceElevated,
    required this.surfaceSunken,
    required this.border,
    required this.borderControl,
    required this.textPrimary,
    required this.textSecondary,
    required this.textMuted,
    required this.focusRing,
    required this.scrim,
    required this.chart1,
    required this.chart2,
    required this.chart3,
    required this.chart4,
    required this.chart5,
  });

  final Color primary;
  final Color onPrimary;
  final Color primaryHover;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color accent;
  final Color onAccent;
  final Color accentContainer;
  final Color onAccentContainer;
  final Color success;
  final Color onSuccess;
  final Color successContainer;
  final Color onSuccessContainer;
  final Color warning;
  final Color onWarning;
  final Color warningContainer;
  final Color onWarningContainer;
  final Color danger;
  final Color onDanger;
  final Color dangerContainer;
  final Color onDangerContainer;
  final Color info;
  final Color onInfo;
  final Color infoContainer;
  final Color onInfoContainer;
  final Color background;
  final Color surface;
  final Color surfaceElevated;
  final Color surfaceSunken;
  final Color border;
  final Color borderControl;
  final Color textPrimary;
  final Color textSecondary;
  final Color textMuted;
  final Color focusRing;
  final Color scrim;
  final Color chart1;
  final Color chart2;
  final Color chart3;
  final Color chart4;
  final Color chart5;

  static const light = AppColors(
    primary: Color(0xFF0F615D),
    onPrimary: Color(0xFFFFFFFF),
    primaryHover: Color(0xFF0C4B49),
    primaryContainer: Color(0xFFE8F6F5),
    onPrimaryContainer: Color(0xFF0C4B49),
    secondary: Color(0xFF1F3557),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFEBF0F7),
    onSecondaryContainer: Color(0xFF1F3557),
    accent: Color(0xFF5C4BCB),
    onAccent: Color(0xFFFFFFFF),
    accentContainer: Color(0xFFF0EEFD),
    onAccentContainer: Color(0xFF3A2F84),
    success: Color(0xFF1A6B48),
    onSuccess: Color(0xFFFFFFFF),
    successContainer: Color(0xFFE7F6EE),
    onSuccessContainer: Color(0xFF0F3F2B),
    warning: Color(0xFF8A5A00),
    onWarning: Color(0xFFFFFFFF),
    warningContainer: Color(0xFFFFF6E0),
    onWarningContainer: Color(0xFF4A3000),
    danger: Color(0xFFB93030),
    onDanger: Color(0xFFFFFFFF),
    dangerContainer: Color(0xFFFDECEC),
    onDangerContainer: Color(0xFF501313),
    info: Color(0xFF1A54A6),
    onInfo: Color(0xFFFFFFFF),
    infoContainer: Color(0xFFE9F1FD),
    onInfoContainer: Color(0xFF0F2F5E),
    background: Color(0xFFF3F7F6),
    surface: Color(0xFFFFFFFF),
    surfaceElevated: Color(0xFFFFFFFF),
    surfaceSunken: Color(0xFFE4EBEA),
    border: Color(0xFFCFD9D8),
    borderControl: Color(0xFF788A8B),
    textPrimary: Color(0xFF121B1D),
    textSecondary: Color(0xFF465759),
    textMuted: Color(0xFF55686A),
    focusRing: Color(0xFF5C4BCB),
    scrim: Color(0xFF0A1112),
    chart1: Color(0xFF157772),
    chart2: Color(0xFF7263E0),
    chart3: Color(0xFFB37700),
    chart4: Color(0xFF1F68CC),
    chart5: Color(0xFFD95B3E),
  );
  static const dark = AppColors(
    primary: Color(0xFF66C2BB),
    onPrimary: Color(0xFF0A1112),
    primaryHover: Color(0xFF9BDAD5),
    primaryContainer: Color(0xFF083634),
    onPrimaryContainer: Color(0xFFC9EBE8),
    secondary: Color(0xFF8FA8CB),
    onSecondary: Color(0xFF0A1112),
    secondaryContainer: Color(0xFF16253F),
    onSecondaryContainer: Color(0xFFD3DEEE),
    accent: Color(0xFFA79DF1),
    onAccent: Color(0xFF0A1112),
    accentContainer: Color(0xFF2A2260),
    onAccentContainer: Color(0xFFE0DCFB),
    success: Color(0xFF7CCBA3),
    onSuccess: Color(0xFF0A1112),
    successContainer: Color(0xFF0F3F2B),
    onSuccessContainer: Color(0xFFC5EAD5),
    warning: Color(0xFFF5C453),
    onWarning: Color(0xFF0A1112),
    warningContainer: Color(0xFF4A3000),
    onWarningContainer: Color(0xFFFFE8B0),
    danger: Color(0xFFEE8F8F),
    onDanger: Color(0xFF0A1112),
    dangerContainer: Color(0xFF501313),
    onDangerContainer: Color(0xFFF9CFCF),
    info: Color(0xFF7FB0F0),
    onInfo: Color(0xFF0A1112),
    infoContainer: Color(0xFF0F2F5E),
    onInfoContainer: Color(0xFFCCE0FA),
    background: Color(0xFF0A1112),
    surface: Color(0xFF121B1D),
    surfaceElevated: Color(0xFF1A2527),
    surfaceSunken: Color(0xFF0E1618),
    border: Color(0xFF364446),
    borderControl: Color(0xFF788A8B),
    textPrimary: Color(0xFFE9F0EF),
    textSecondary: Color(0xFFB4C2C2),
    textMuted: Color(0xFF93A5A6),
    focusRing: Color(0xFFA79DF1),
    scrim: Color(0xFF0A1112),
    chart1: Color(0xFF66C2BB),
    chart2: Color(0xFFA79DF1),
    chart3: Color(0xFFF5C453),
    chart4: Color(0xFF7FB0F0),
    chart5: Color(0xFFFFB4A2),
  );
}

abstract final class Space {
  static const double s0 = 0;
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
  static const double s20 = 80;
}

abstract final class Radii {
  static const double none = 0;
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 12;
  static const double lg = 16;
  static const double xl = 24;
  static const double pill = 999;
}

abstract final class IconSizes {
  static const double xs = 16;
  static const double sm = 20;
  static const double md = 24;
  static const double lg = 32;
  static const double xl = 48;
}

abstract final class ControlHeights {
  static const double sm = 36;
  static const double md = 44;
  static const double lg = 52;
  static const double touchTargetMin = 44;
}

abstract final class Breakpoints {
  static const double compact = 0;
  static const double medium = 600;
  static const double expanded = 1024;
  static const double large = 1440;
}

abstract final class LayoutTokens {
  static const double sidebarWidth = 264;
  static const double railWidth = 76;
  static const double topbarHeight = 64;
  static const double bottomNavHeight = 72;
  static const double contentMaxWidth = 1200;
  static const double gutterCompact = 16;
  static const double gutterMedium = 24;
  static const double gutterExpanded = 32;
}

abstract final class Motion {
  static const Duration instant = Duration(milliseconds: 80);
  static const Duration fast = Duration(milliseconds: 140);
  static const Duration base = Duration(milliseconds: 220);
  static const Duration slow = Duration(milliseconds: 360);
  static const Curve standard = Cubic(0.2, 0, 0, 1);
  static const Curve decelerate = Cubic(0, 0, 0, 1);
  static const Curve accelerate = Cubic(0.3, 0, 1, 1);
}

class TypeToken {
  const TypeToken(this.size, this.line, this.weight);
  final double size;
  final double line;
  final FontWeight weight;
  double get height => line / size;
}

abstract final class TypeScale {
  static const String fontFamily = 'Vazirmatn';
  static const display = TypeToken(40, 52, FontWeight.w700);
  static const h1 = TypeToken(32, 44, FontWeight.w700);
  static const h2 = TypeToken(26, 38, FontWeight.w700);
  static const h3 = TypeToken(21, 32, FontWeight.w600);
  static const h4 = TypeToken(17, 28, FontWeight.w600);
  static const body = TypeToken(16, 28, FontWeight.w400);
  static const bodySmall = TypeToken(14, 24, FontWeight.w400);
  static const caption = TypeToken(12, 20, FontWeight.w400);
  static const label = TypeToken(13, 20, FontWeight.w500);
  static const button = TypeToken(15, 24, FontWeight.w600);
}

abstract final class TypeScaleCompact {
  static const display = TypeToken(32, 44, FontWeight.w700);
  static const h1 = TypeToken(26, 38, FontWeight.w700);
  static const h2 = TypeToken(22, 34, FontWeight.w700);
  static const h3 = TypeToken(19, 30, FontWeight.w600);
}

abstract final class Elevations {
  static const light = <int, List<BoxShadow>>{
    0: [],
    1: [
      BoxShadow(
        color: Color.fromRGBO(10, 17, 18, 0.06),
        offset: Offset(0, 1),
        blurRadius: 2,
        spreadRadius: 0,
      ),
    ],
    2: [
      BoxShadow(
        color: Color.fromRGBO(10, 17, 18, 0.07),
        offset: Offset(0, 2),
        blurRadius: 6,
        spreadRadius: 0,
      ),
      BoxShadow(
        color: Color.fromRGBO(10, 17, 18, 0.05),
        offset: Offset(0, 1),
        blurRadius: 2,
        spreadRadius: 0,
      ),
    ],
    3: [
      BoxShadow(
        color: Color.fromRGBO(10, 17, 18, 0.12),
        offset: Offset(0, 8),
        blurRadius: 20,
        spreadRadius: -4,
      ),
      BoxShadow(
        color: Color.fromRGBO(10, 17, 18, 0.06),
        offset: Offset(0, 2),
        blurRadius: 6,
        spreadRadius: 0,
      ),
    ],
    4: [
      BoxShadow(
        color: Color.fromRGBO(10, 17, 18, 0.18),
        offset: Offset(0, 16),
        blurRadius: 40,
        spreadRadius: -8,
      ),
      BoxShadow(
        color: Color.fromRGBO(10, 17, 18, 0.08),
        offset: Offset(0, 4),
        blurRadius: 12,
        spreadRadius: 0,
      ),
    ],
  };
  static const dark = <int, List<BoxShadow>>{
    0: [],
    1: [
      BoxShadow(
        color: Color.fromRGBO(0, 0, 0, 0.4),
        offset: Offset(0, 1),
        blurRadius: 2,
        spreadRadius: 0,
      ),
    ],
    2: [
      BoxShadow(
        color: Color.fromRGBO(0, 0, 0, 0.45),
        offset: Offset(0, 2),
        blurRadius: 6,
        spreadRadius: 0,
      ),
    ],
    3: [
      BoxShadow(
        color: Color.fromRGBO(0, 0, 0, 0.55),
        offset: Offset(0, 8),
        blurRadius: 20,
        spreadRadius: -4,
      ),
    ],
    4: [
      BoxShadow(
        color: Color.fromRGBO(0, 0, 0, 0.65),
        offset: Offset(0, 16),
        blurRadius: 40,
        spreadRadius: -8,
      ),
    ],
  };
}
