// <auto-generated />
using System;
using MedSmarter.Modules.Consent.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSmarter.Modules.Consent.Persistence.Migrations
{
    [DbContext(typeof(ConsentDbContext))]
    partial class ConsentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("consent")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSmarter.Modules.Consent.ConsentEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("ConsentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.HasKey("Id")
                        .HasName("pk_consent_event");

                    b.HasIndex("ConsentId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_consent_event_consent_id_kind");

                    b.HasIndex("SubjectUserId", "At")
                        .HasDatabaseName("ix_consent_event_subject_user_id_at");

                    b.ToTable("consent_event", "consent");
                });

            modelBuilder.Entity("MedSmarter.Modules.Consent.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GranteeOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("grantee_organization_id");

                    b.Property<Guid?>("GranteeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("grantee_user_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string[]>("Scope")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scope");

                    b.Property<Guid>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_consent");

                    b.HasIndex("GranteeOrganizationId")
                        .HasDatabaseName("ix_consent_grantee_organization_id");

                    b.HasIndex("GranteeUserId")
                        .HasDatabaseName("ix_consent_grantee_user_id");

                    b.HasIndex("SubjectUserId", "GrantedAt")
                        .HasDatabaseName("ix_consent_subject_user_id_granted_at");

                    b.ToTable("consent", "consent", t =>
                        {
                            t.HasCheckConstraint("ck_consent_expires_after_grant", "expires_at > granted_at");

                            t.HasCheckConstraint("ck_consent_one_grantee_at_most", "NOT (grantee_user_id IS NOT NULL AND grantee_organization_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_consent_scope_not_empty", "cardinality(scope) > 0");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Consent.ConsentEventRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Consent.ConsentRecord", null)
                        .WithMany()
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consent_event_consent_id");
                });
#pragma warning restore 612, 618
        }
    }
}
