// <auto-generated />
using System;
using MedSmarter.Modules.Guidance.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSmarter.Modules.Guidance.Persistence.Migrations
{
    [DbContext(typeof(GuidanceDbContext))]
    [Migration("20261010195956_AddGuidanceOrigin")]
    partial class AddGuidanceOrigin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("guidance")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSmarter.Modules.Guidance.Persistence.GuidanceEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ActorIsProfessional")
                        .HasColumnType("boolean")
                        .HasColumnName("actor_is_professional");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_status");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_guidance_status_event");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_guidance_status_event_message_id");

                    b.ToTable("guidance_status_event", "guidance");
                });

            modelBuilder.Entity("MedSmarter.Modules.Guidance.Persistence.GuidanceMessageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("level");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<Guid?>("OriginAssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_assessment_id");

                    b.Property<DateTimeOffset?>("OriginDataAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("origin_data_as_of");

                    b.Property<string>("OriginFindingKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("origin_finding_key");

                    b.Property<string>("OriginKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin_kind");

                    b.Property<string>("OriginRuleId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("origin_rule_id");

                    b.Property<int?>("OriginRuleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("origin_rule_version");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("patient_json");

                    b.Property<string>("ProfessionalJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("professional_json");

                    b.Property<DateTimeOffset?>("ReferredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("referred_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("template_key");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_guidance_message");

                    b.HasIndex("PatientId", "CreatedAt")
                        .HasDatabaseName("ix_guidance_message_patient_id_created_at");

                    b.HasIndex("PatientId", "OriginFindingKey")
                        .HasDatabaseName("ix_guidance_message_patient_id_origin_finding_key");

                    b.ToTable("guidance_message", "guidance");
                });

            modelBuilder.Entity("MedSmarter.Modules.Guidance.Persistence.GuidanceEventRow", b =>
                {
                    b.HasOne("MedSmarter.Modules.Guidance.Persistence.GuidanceMessageRow", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guidance_status_event_guidance_message_message_id");
                });
#pragma warning restore 612, 618
        }
    }
}
