<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MedSmarter.BuildingBlocks\MedSmarter.BuildingBlocks.csproj" />
    <ProjectReference Include="..\MedSmarter.Modules.Pharmacies.Contracts\MedSmarter.Modules.Pharmacies.Contracts.csproj" />
  </ItemGroup>
</Project>
