// <auto-generated />
using System;
using MedSmarter.Modules.Patients.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedSmarter.Modules.Patients.Persistence.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    partial class PatientsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("patients")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.AllergyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Reaction")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reaction");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("substance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_patient_allergy");

                    b.HasIndex("PatientId", "DeletedAt")
                        .HasDatabaseName("ix_patient_allergy_patient_id_deleted_at");

                    b.ToTable("patient_allergy", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_allergy_medication_kind", "medication_id IS NULL OR kind = 'Medication'");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.CareRelationshipEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("relationship_id");

                    b.HasKey("Id")
                        .HasName("pk_care_relationship_event");

                    b.HasIndex("RelationshipId")
                        .HasDatabaseName("ix_care_relationship_event_relationship_id");

                    b.ToTable("care_relationship_event", "patients");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.CareRelationshipRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EndReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid?>("EndedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("initiated_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("PatientConsentedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("patient_consented_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PatientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_user_id");

                    b.Property<DateTimeOffset?>("ProviderConsentedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_consented_at");

                    b.Property<Guid?>("ProviderOrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_organization_id");

                    b.Property<Guid?>("ProviderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_user_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_care_relationship");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_care_relationship_patient_id");

                    b.HasIndex("PatientUserId", "Status")
                        .HasDatabaseName("ix_care_relationship_patient_user_id_status");

                    b.HasIndex("ProviderUserId", "Status")
                        .HasDatabaseName("ix_care_relationship_provider_user_id_status");

                    b.HasIndex("PatientUserId", "ProviderOrganizationId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_care_relationship_patient_user_id_provider_organization_id_kind")
                        .HasFilter("provider_organization_id IS NOT NULL AND status IN ('PendingProvider', 'PendingPatient', 'Active')");

                    b.HasIndex("PatientUserId", "ProviderUserId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_care_relationship_patient_user_id_provider_user_id_kind")
                        .HasFilter("provider_user_id IS NOT NULL AND status IN ('PendingProvider', 'PendingPatient', 'Active')");

                    b.ToTable("care_relationship", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_care_relationship_has_provider", "provider_user_id IS NOT NULL OR provider_organization_id IS NOT NULL");

                            t.HasCheckConstraint("ck_care_relationship_not_self", "patient_user_id <> provider_user_id");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ConditionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("OnsetDate")
                        .HasColumnType("date")
                        .HasColumnName("onset_date");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_patient_condition");

                    b.HasIndex("PatientId", "DeletedAt")
                        .HasDatabaseName("ix_patient_condition_patient_id_deleted_at");

                    b.ToTable("patient_condition", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_condition_name", "length(name) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.DataCategoryRecord", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.HasKey("PatientId", "Category")
                        .HasName("pk_patient_data_snapshot_meta");

                    b.ToTable("patient_data_snapshot_meta", "patients");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ExternalIdentifierRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<Guid?>("LinkedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_by");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scheme");

                    b.Property<string>("ValueHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("value_hash");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_external_patient_identifier");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_external_patient_identifier_patient_id");

                    b.HasIndex("Scheme", "ValueHash")
                        .IsUnique()
                        .HasDatabaseName("ux_external_patient_identifier_scheme_value_hash");

                    b.ToTable("external_patient_identifier", "patients");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.IntakeLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PatientMedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_medication_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<Guid?>("ScheduleEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_entry_id");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.HasKey("Id")
                        .HasName("pk_medication_intake_log");

                    b.HasIndex("PatientMedicationId")
                        .HasDatabaseName("ix_medication_intake_log_patient_medication_id");

                    b.HasIndex("PatientId", "RecordedAt")
                        .HasDatabaseName("ix_medication_intake_log_patient_id_recorded_at");

                    b.HasIndex("ScheduleEntryId", "ScheduledFor")
                        .IsUnique()
                        .HasDatabaseName("ux_medication_intake_log_schedule_entry_id_scheduled_for")
                        .HasFilter("schedule_entry_id IS NOT NULL AND scheduled_for IS NOT NULL");

                    b.ToTable("medication_intake_log", "patients");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.MedicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("DoseAmount")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("dose_amount");

                    b.Property<string>("DoseText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose_text");

                    b.Property<string>("DoseUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dose_unit");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("frequency");

                    b.Property<int?>("FrequencyValue")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_value");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PrescriberNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prescriber_note");

                    b.Property<string>("Route")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("route");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StopReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stop_reason");

                    b.Property<string>("UnregisteredName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("unregistered_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_patient_medication");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("ix_patient_medication_medication_id");

                    b.HasIndex("PatientId", "Status", "DeletedAt")
                        .HasDatabaseName("ix_patient_medication_patient_id_status_deleted_at");

                    b.ToTable("patient_medication", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_medication_dates", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_patient_medication_dose", "(dose_amount IS NULL AND dose_unit IS NULL) OR (dose_amount > 0 AND dose_unit IS NOT NULL)");

                            t.HasCheckConstraint("ck_patient_medication_identity", "medication_id IS NOT NULL OR (unregistered_name IS NOT NULL AND length(unregistered_name) > 0)");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_patient");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_user_id");

                    b.ToTable("patient", "patients");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ProfileRecord", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("height_cm");

                    b.Property<string>("Sex")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sex");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_kg");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_birth");

                    b.HasKey("PatientId")
                        .HasName("pk_patient_profile");

                    b.ToTable("patient_profile", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_patient_profile_height", "height_cm IS NULL OR (height_cm > 0 AND height_cm <= 260)");

                            t.HasCheckConstraint("ck_patient_profile_weight", "weight_kg IS NULL OR (weight_kg > 0 AND weight_kg <= 500)");

                            t.HasCheckConstraint("ck_patient_profile_year_of_birth", "year_of_birth IS NULL OR (year_of_birth BETWEEN 1900 AND 2200)");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.RecordVersionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("record_type");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_patient_record_version");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_record_version_patient_id");

                    b.HasIndex("RecordType", "RecordId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_record_version_record_type_record_id_version_number");

                    b.ToTable("patient_record_version", "patients");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ScheduleEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DaysMask")
                        .HasColumnType("integer")
                        .HasColumnName("days_mask");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PatientMedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_medication_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeOnly>("TimeOfDay")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_of_day");

                    b.HasKey("Id")
                        .HasName("pk_medication_schedule_entry");

                    b.HasIndex("PatientMedicationId")
                        .HasDatabaseName("ix_medication_schedule_entry_patient_medication_id");

                    b.HasIndex("PatientId", "PatientMedicationId")
                        .HasDatabaseName("ix_medication_schedule_entry_patient_id_patient_medication_id");

                    b.ToTable("medication_schedule_entry", "patients", t =>
                        {
                            t.HasCheckConstraint("ck_medication_schedule_entry_days", "days_mask BETWEEN 1 AND 127");
                        });
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.SymptomRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OnsetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onset_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PatientMedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_medication_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_patient_symptom_report");

                    b.HasIndex("PatientId", "OnsetAt")
                        .HasDatabaseName("ix_patient_symptom_report_patient_id_onset_at");

                    b.ToTable("patient_symptom_report", "patients");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.AllergyRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_allergy_patient_patient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.CareRelationshipEventRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.CareRelationshipRecord", null)
                        .WithMany()
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_relationship_event_care_relationship_relationship_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.CareRelationshipRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_relationship_patient_patient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ConditionRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_condition_patient_patient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.DataCategoryRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_data_snapshot_meta_patient_patient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ExternalIdentifierRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_external_patient_identifier_patient_patient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.IntakeLogRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.MedicationRecord", null)
                        .WithMany()
                        .HasForeignKey("PatientMedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_intake_log_patient_medication_patient_medication_id");

                    b.HasOne("MedSmarter.Modules.Patients.Persistence.ScheduleEntryRecord", null)
                        .WithMany()
                        .HasForeignKey("ScheduleEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medication_intake_log_medication_schedule_entry_schedule_entry_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.MedicationRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_medication_patient_patient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ProfileRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithOne()
                        .HasForeignKey("MedSmarter.Modules.Patients.Persistence.ProfileRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_profile_patient_patient_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.ScheduleEntryRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.MedicationRecord", null)
                        .WithMany()
                        .HasForeignKey("PatientMedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_schedule_entry_patient_medication_patient_medication_id");
                });

            modelBuilder.Entity("MedSmarter.Modules.Patients.Persistence.SymptomRecord", b =>
                {
                    b.HasOne("MedSmarter.Modules.Patients.Persistence.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_symptom_report_patient_patient_id");
                });
#pragma warning restore 612, 618
        }
    }
}
